name: Skywarz
version: '${project.version}'
main: io.github.aparx.skywarz.startup.Main
author: "aparx (@bonedfps)"
api-version: 1.14
description: "An intriguing Skywars minigame plugin"

website: "https://www.spigotmc.org/resources/skywarz.42739/"

commands:
  skywarz:
    usage: "/skywarz <...>"
    aliases: [ "sw", "skywars" ]

permissions:
  skywarz.play:
    description: "Allows a player to join a match (required for bungeecord)"
    default: true
  # VIP permissions
  skywarz.priority:
    description: "Allows to have priority when a lobby is full"
  skywarz.quickstart:
    description: "Allows to skip the lobby timer and quickly start the game"
  # Stat permissions
  skywarz.stats.self:
    description: "Allows to see their own Skywarz statistics"
    default: true
  skywarz.stats.other:
    description: "Allows to see other people's Skywarz statistics"
    default: true
  skywarz.stats.modify:
    description: "Allows to modify the statistics of people"
  skywarz.stats.*:
    description: "User can see everybody's statistics and manipulate them"
    children:
      skywarz.stats.self: true
      skywarz.stats.other: true
      skywarz.stats.modify: true
  # Admin permissions
  skywarz.setup:
    description: "Allows to create, delete and manage Skywarz matches, arenas and more"
  skywarz.*:
    description: "Allows the player to do everything in Skywarz"
    children:
      skywarz.priority: true
      skywarz.setup: true
      skywarz.play: true
      skywarz.quickstart: true
      skywarz.stats.*: true
